#!/bin/bash

dataset=$1
epochs=10

alphas=(0.5 1 2 4)
weights=(0.5 1 2 4)

outf="data/out/${dataset}_p(f|e)_normalized_results.csv"

./plain_best_paths $dataset
printf "ASR 1-best: " > $outf
python ../nlp/per.py \
		--ref data/fisher-callhome/corpus/ldc/${dataset}.es.nopunc.lower \
		--hypo data/out/plain_best_paths/${dataset}.es >> $outf
printf "score\tepochs\talpha\tweight\n" >> $outf
for alpha in "${alphas[@]}"; do
	for weight in "${weights[@]}"; do
		./run $dataset $epochs $alpha $weight
		./wer $dataset $epochs $alpha $weight >> $outf
		printf "\t${epochs}\t${alpha}\t${weight}\n" >> $outf
	done
done
